server:
  port: 9998
security:
  ignored: /rest/registrations/*,/rest/registrations,/new-account*,/sdoc.jsp,/*.js,/api-docs,/api-docs/default/*,/images/*,/lib/*,/css/*

spring.oauth2:
  client:
    accessTokenUri: ${vcap.services.sso.credentials.tokenUri}
    userAuthorizationUri: ${vcap.services.sso.credentials.authorizationUri}
    clientId: ${vcap.services.sso.credentials.clientId}
    clientSecret: ${vcap.services.sso.credentials.clientSecret}

  resource:
    id: cloud_controller
    jwt:
      keyUri: ${vcap.services.sso.credentials.tokenKey}
    userInfoUri: ${vcap.services.sso.credentials.userInfoUri}
  check_token: ${vcap.services.sso.credentials.checkTokenUri}

oauth:
  resource: ${vcap.services.sso.credentials.apiEndpoint}
  uaa: ${vcap.services.sso.credentials.uaaUri}

smtp:
  host: ${vcap.services.smtp.credentials.host}
  port: ${vcap.services.smtp.credentials.port}
  protocol: ${vcap.services.smtp.credentials.protocol}
  username: ${vcap.services.smtp.credentials.username}
  password: ${vcap.services.smtp.credentials.password}
  email: ${vcap.services.sso.credentials.email}
  timeout: 5000
  debug: true
  #List of blocked domain. Adding new domain after comma: example.com,foo.com
  forbidden_domains: ${vcap.services.smtp.credentials.forbidden_domains:example.com}
  email_name: ${vcap.services.smtp.credentials.email_name:TrustedAnalytics}

web:
  debug: false

app:
   url: ${vcap.application.uris[0]:}
   console:
       host: console
       useSsl: true

endpoints.metrics.enabled: true
spring.profiles.active: cloud,in-memory

logging:
  level:
    org.trustedanalytics: DEBUG
    org.springframework.security: DEBUG
